version: "3.7"

services:
  frontend:
    build:
      context: ./aws-instance-manager
      dockerfile: Dockerfile
      args:
        REACT_APP_API_URL: "http://0.0.0.0:3000"
    ports:
      - "80:80"
    depends_on:
      - api

  api:
    build:
      context: ./api
      dockerfile: Dockerfile
    ports:
      - "8000:80"
